// <auto-generated />
using HomeCenterTest.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace HomeCenterTest.Infrastructure.Migrations
{
    [DbContext(typeof(CarCenterContext))]
    [Migration("20211106094459_Migration4")]
    partial class Migration4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HomeCenterTest.Core.Entities.TipoIdentificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("TipoIdenti")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasColumnName("TipoIdenti");

                    b.HasKey("Id")
                        .HasName("Pk_TipoIdentificacion");

                    b.ToTable("TipoIdentificacion");
                });
#pragma warning restore 612, 618
        }
    }
}
